### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ThatGreedyCorpus** [Empyrrhus/MIDI-To-Shawzin#1]
I put the midi file into the midi to shawzin app and nothing happens

**Comment by Empyrrhus** [comment]
Which midi file did you use? Also, are you using the latest version?

**Comment by Empyrrhus** [comment]
Well, the app has [been updated ](https://github.com/Empyrrhus/MIDI-To-Shawzin/releases/)since this post, and [has likely been fixed](https://github.com/Empyrrhus/MIDI-To-Shawzin/issues/2). If you're still having problems, feel free to open a new issue.
