### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by cyanmagentayellow** [Empyrrhus/MIDI-To-Shawzin#3]
Hi, it seems like the new Yo scale messed something up, strings produced are all invalid

**Comment by Empyrrhus** [comment]
Are you using the [latest version](https://github.com/Empyrrhus/MIDI-To-Shawzin/releases/tag/1.4)?

**Comment by cyanmagentayellow** [comment]
my bad, i didn't see it. by the way did you ever meet the issue where some notes after converted from midi to string will be kinda off timing? i got that issue even when the song is on low speed

**Comment by Empyrrhus** [comment]
Not really. If you have a particular MIDI file in mind, you can attach a file to a comment and I'll take a look at it.

**Comment by cyanmagentayellow** [comment]
[blacksabbath.zip](https://github.com/Empyrrhus/MIDI-To-Shawzin/files/3637286/blacksabbath.zip)

here, i use 3 (chromatic) for scale, 0.5 for speed

**Comment by Empyrrhus** [comment]
The correct playback speed varies from file to file, the program usually gets the right speed but not always. For now, just tweak the values until it sounds right. The blacksabbath.mid file in particular seems to sync at [about 0.58 speed](https://www.youtube.com/watch?v=CzS6rMXHJGA&feature=youtu.be).

**Comment by cyanmagentayellow** [comment]
It still somehow be off timing for me, you can try this mid file to see it clearer, I put 64 16th notes in a row, one after another, which means all the notes should be at the same distance, but when I import the string into warframe there's some places that are different from the rest.
[test 16 4.zip](https://github.com/Empyrrhus/MIDI-To-Shawzin/files/3638343/test.16.4.zip)

**Comment by Empyrrhus** [comment]
Ah, that's actually a technical issue with how the Shawzin is implemented. When recording or importing Shawzin songs, notes must be multiples of 0.0625s apart; in other words, a maximum of 64 notes within 4 seconds (1 measure). Quarter notes that are exactly 1s apart and eighth notes 0.5s apart would work as well.
MIDI files are significantly more precise than this, and aren't limited to that specific tempo. However if the tempo is not a multiple of the Shawzin's tempo (64th notes every 0.0625s), then eventually it will de-synchronize, and the program will have to round which 0.0625s interval the note is in; so you may get a short pause or two notes suddenly close together.
In the case of the test MIDI file, the 16th notes are not exactly multiples of 0.25s apart at 0.4x speed modifier. A bit of trial and error reveals that it syncs up with the Shawzin's tempo at a speed modifier of 0.425 (and any multiple of it).

**Comment by cyanmagentayellow** [comment]
Great explanation, i got it now. Thank you very much
