### ISSUE TITLE
It doesn't work with Ableton MIDIs?

### ISSUE THREAD

**Issue by cyanmagentayellow** [Empyrrhus/MIDI-To-Shawzin#4]
Can you have a check, I just tried Ableton today to make MIDIs, when I imported them the option to choose scale and speed appeared but then nothing happened, no txt files, Midi-to-shawzin just closed.
[ableton.zip](https://github.com/Empyrrhus/MIDI-To-Shawzin/files/3640104/ableton.zip)

**Comment by Empyrrhus** [comment]
Alright, see if [Version 1.4.1](https://github.com/Empyrrhus/MIDI-To-Shawzin/releases/tag/1.4.1) fixes it?

**Comment by cyanmagentayellow** [comment]
It does convert the ableton midis now, but whatever speed modifier value i put in the outcomes just stay at a same speed, and note at 0.0s is always impossible. 
[MID C3.zip](https://github.com/Empyrrhus/MIDI-To-Shawzin/files/3640893/MID.C3.zip)

In one of the files I tried (accidentally deleted it), notes at 0s, 1s, 2s, 3s,... were impossible too, and G# notes were out of scale (i put scale input as 3)

Btw I saw in the change log you said the tempo detected would be in Debug txt, is it the "time" in Debug text or something else?

**Comment by Empyrrhus** [comment]
> Btw I saw in the change log you said the tempo detected would be in Debug txt, is it the "time" in Debug text or something else?

It will be listed on its own separate line as
`Ticks per Beat = XXX` or `Tempo = XXXXXX`, if found.


> In one of the files I tried (accidentally deleted it), notes at 0s, 1s, 2s, 3s,... were impossible too,

The default playback speed was too high, causing multiple incompatible notes (in this case, two of the same note) to occupy the same interval, and thus was considered impossible to import.


> and G# notes were out of scale (i put scale input as 3)

I couldn't replicate this issue on my end.

**See if [Version 1.4.2](https://github.com/Empyrrhus/MIDI-To-Shawzin/releases/tag/1.4.2) fixes these problems.**

**Comment by cyanmagentayellow** [comment]
Nice, all seems fine now.

Oh and do you have suggestion for any value in the outcome txt files that i should look at in order to set a more suitable speed modifier (like the last time when you found out 0.425 made the midi and Shawzin tempo sync up) or just keep trying and changing numbers until it fits? 
Like I kinda get the idea when you explained those issues with the Shawzin, but didn't know how you pulled out "0.425".

**Comment by Empyrrhus** [comment]
If you want to calculate it, you can use the length of the MIDI file and the length of the Shawzin song at playback speed 1x. You can determine the length of the Shawzin song by looking at the last two characters, and checking the character table in [my notes](https://www.reddit.com/r/Warframe/comments/cxbxoc/shawzin_song_recording_syntax/).

Take for example, if the last two characters were "Cg":
 - Check the table for the first character and find the corresponding measure, then subtract 1 and multiply by 4 seconds. 
`For the character "C" in our example, that's measure 3. Subtracting 1 then multiplying by 4 seconds yields (3-1)*4 = 8 seconds.`
 - Then take the last character and find the corresponding note timing.
`In the case of "g", that would be 32/64. `
 - Find the product of this fraction and 4 seconds.
`(32/64) * 4 seconds = 2 seconds`
 - The length of the Shawzin song is the sum of these two values. 
`8s + 2s = 10s`
 - The correct speed modifier is equal to the length of the Shawzin song divided by the timestamp of the last note in the MIDI file. 
`So if the last note in the MIDI file starts at the 20 second mark, then the correct playback speed modifier would be (10s/20s), or 0.5x.`

_Personally_, I think it's faster to just keep trying and changing numbers until it fits, but either way works.

Your MIDI files were a bit of a special case, as they don't seem to declare a tempo. Therefore, the program used the default tempo value instead (which in your case, was too fast).

**Comment by Empyrrhus** [comment]
With [Version 1.4.3](https://github.com/Empyrrhus/MIDI-To-Shawzin/releases/tag/1.4.3), just scroll down to the bottom of the DEBUG file, and the timestamp of the last note will tell you the length of the Shawzin song.

**Comment by cyanmagentayellow** [comment]
Thank you for taking your time answering all that. I really like that Legos part, haha.

**Comment by cyanmagentayellow** [comment]
> If you want to calculate it, you can use the length of the MIDI file and the length of the Shawzin song at playback speed 1x. You can determine the length of the Shawzin song by looking at the last two characters of the import string, and referencing the character table in [my notes](https://www.reddit.com/r/Warframe/comments/cxbxoc/shawzin_song_recording_syntax/).
> 
> Take for example, if the last two characters were "Cg":
> 
> * Check the table for the first character and find the corresponding measure, then subtract 1 and multiply by 4 seconds.
>   `For the character "C" in our example, that's measure 3. Subtracting 1 then multiplying by 4 seconds yields (3-1)*4 = 8 seconds.`
> * Then take the last character and find the corresponding note timing.
>   `In the case of "g", that would be 32/64. `
> * Find the product of this fraction and 4 seconds.
>   `(32/64) * 4 seconds = 2 seconds`
> * The length of the Shawzin song is the sum of these two values.
>   `8s + 2s = 10s`
> * The correct speed modifier is equal to the length of the Shawzin song divided by the timestamp of the last note in the MIDI file.
>   `So if the last note in the MIDI file starts at the 20 second mark, then the correct playback speed modifier would be (10s/20s), or 0.5x.`
> 
> _Personally_, I think it's faster to just keep trying and changing numbers until it fits, but either way works.
> 
> Your MIDI files were a bit of a special case, as they don't seem to declare a tempo. Therefore, the program used the default tempo value instead (which in your case, was too fast).
> 
> > ...sometimes I use this man's tool: https://theguywiththehat.github.io/shawzin/#/ and the outcome strings always give notes on consistent lengths with no weird gaps.
> 
> Even though it's not explicitly stated, each note placed in that tool occupies exact 0.0625s intervals. You technically don't need to know that to build Shawzin import strings; you just build the import string 16th note by 16th note, with some amount of 16th notes' worth of silence in-between. Again, [my notes](https://www.reddit.com/r/Warframe/comments/cxbxoc/shawzin_song_recording_syntax/) go into great detail on how to create Shawzin import strings.
> 
> As an analogy, the Shawzin composer program is like building with Legos. The MIDI-To-Shawzin program is like whittling your Legos out of wood first, only to realize they're the wrong size. 🙃

Oh I forgot to ask you this, so based on the limitations of the Shawzin, there's no way the notes with more complex timings such as triplets and the like would work?

**Comment by Empyrrhus** [comment]
Assuming you have a song that's synchronized, triplets will be cleanly possible by multiplying the playback speed modifier by 0.888888. Now instead of one measure containing 64 64th notes, one measure now contains 72 64th notes. We use the number 72 because it is divisible by both 3 and 4, allowing triplets to work with correct timing. The playback speed modifier is therefore multiplied by 64 / 72 = 0.888888.

In the Shawzin song composer, that triplet would look like this:
<p align="center">
    <img src="https://i.imgur.com/iewoIj7.png">
</p>
